const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#7c3aed",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#7c3aed",
    primaryForeground: "#ffffff",
    secondary: "#f4f4f5",
    secondaryForeground: "#18181b",
    muted: "#f4f4f5",
    mutedForeground: "#71717a",
    accent: "#f4f4f5",
    accentForeground: "#18181b",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e4e4e7",
    input: "#e4e4e7",
    ring: "#7c3aed",
    surface: "#fafafa",
  },
  dark: {
    text: "#fafafa",
    tint: "#8b5cf6",
    background: "#09090b",
    foreground: "#fafafa",
    card: "#18181b",
    cardForeground: "#fafafa",
    primary: "#8b5cf6",
    primaryForeground: "#09090b",
    secondary: "#27272a",
    secondaryForeground: "#fafafa",
    muted: "#27272a",
    mutedForeground: "#a1a1aa",
    accent: "#27272a",
    accentForeground: "#fafafa",
    destructive: "#dc2626",
    destructiveForeground: "#fafafa",
    border: "#27272a",
    input: "#3f3f46",
    ring: "#8b5cf6",
    surface: "#111113",
  },
  radius: 12,
};

export default colors;
