import { Tool } from '@/types/tool';

export const imageTools: Tool[] = [
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    title: 'Image Compressor',
    description: 'Compress PNG, JPEG, and WebP images locally to reduce file size without losing quality.',
    category: 'image',
    icon: 'Image',
    seo: {
      title: 'Image Compressor Online - Compress JPEG, PNG & WebP',
      description: 'Shrink image file size locally in your browser. Choose custom compression qualities securely without uploading files.',
      keywords: ['image compressor', 'compress jpeg', 'reduce image size', 'beautify PNG compressor', 'shrink photo size'],
      overview: 'Large images cause web pages to load slowly. Compressing images re-encodes color pixels and strips unnecessary metadata, resulting in smaller files.',
      howToUse: ['Upload an image (PNG, JPEG, or WebP).', 'Select your target quality percentage using the slider.', 'Review the compressed file size and download your optimized image.'],
      examples: [{ input: { file: 'landscape.jpg', quality: 75 }, output: { originalSize: '4.2 MB', compressedSize: '1.1 MB', savings: '73%' }, explanation: 'Compressing a large camera photo by 25% reduces the file size significantly with near-zero visual degradation.' }],
      faqs: [{ question: 'Does this compromise my privacy?', answer: 'No! All processing is executed client-side in your browser cache. Your photos are never sent to any server.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload Image File', type: 'file', defaultValue: null },
      { name: 'quality', label: 'Compression Quality (%)', type: 'number', defaultValue: 80, unit: '%', slider: { min: 10, max: 100, step: 5 } },
    ],
    outputs: [{ name: 'result', label: 'Compressed Image', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'image-resizer',
    slug: 'image-resizer',
    title: 'Image Resizer',
    description: 'Resize image dimensions (width and height) in pixels or percentage ratio locally.',
    category: 'image',
    icon: 'Maximize',
    seo: {
      title: 'Image Resizer Online - Change Photo Dimensions',
      description: 'Resize image width and height in pixels. Maintain original aspect ratio or stretch layouts.',
      keywords: ['image resizer', 'resize photos', 'change image width height', 'crop dimensions online'],
      overview: 'Adjusting image dimensions fits photos to specific layouts or requirements (such as social media profiles or banners) without server uploads.',
      howToUse: ['Upload an image file.', 'Specify the target width and height in pixels.', 'Toggle Aspect Ratio preservation, then download the resized image.'],
      examples: [{ input: { file: 'banner.png', width: 800, height: 600, maintainRatio: true }, output: { dimensions: '800 x 600 px' }, explanation: 'Resizes the image to fit standard grid layouts.' }],
      faqs: [{ question: 'What does Maintain Aspect Ratio do?', answer: 'It automatically adjusts the height when you change the width (and vice versa) to prevent your image from looking stretched.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload Image File', type: 'file', defaultValue: null },
      { name: 'width', label: 'Target Width (px)', type: 'number', defaultValue: 800 },
      { name: 'height', label: 'Target Height (px)', type: 'number', defaultValue: 600 },
      { name: 'maintainRatio', label: 'Maintain Aspect Ratio', type: 'boolean', defaultValue: true, helpText: 'Keep proportional width and height scaling' },
    ],
    outputs: [{ name: 'result', label: 'Resized Image', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'background-remover',
    slug: 'background-remover',
    title: 'Background Remover',
    description: 'Remove solid colored backgrounds from images and logos locally to generate transparent PNGs.',
    category: 'image',
    icon: 'Scissors',
    seo: {
      title: 'Background Remover Online - Make Transparent PNGs',
      description: 'Remove solid white, black, or custom backgrounds from graphic files locally in the browser.',
      keywords: ['remove background', 'transparent png generator', 'chroma key image', 'clear white background', 'logo background eraser'],
      overview: 'Transparent backgrounds make logos and product photos look professional on slides or websites. This local background remover keys out solid colors inside your browser.',
      howToUse: ['Select or drop your image file.', 'Input the target background hex color (defaulting to white #ffffff).', 'Adjust the tolerance slider to clear anti-aliased edges, then download your transparent PNG.'],
      examples: [{ input: { file: 'logo.jpg', color: '#ffffff', tolerance: 30 }, output: { format: 'PNG (Transparent)' }, explanation: 'Keys out the white surrounding area of a JPG logo, returning a clean transparent PNG.' }],
      faqs: [{ question: 'Does this work on complex backgrounds?', answer: 'This tool is optimized to remove solid color backdrops. Complex multi-colored backgrounds are best processed with AI segmentation tools.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload Image File', type: 'file', defaultValue: null },
      { name: 'bgColor', label: 'Target Background Color (Hex)', type: 'text', defaultValue: '#ffffff', placeholder: 'e.g. #ffffff' },
      { name: 'tolerance', label: 'Color Tolerance (%)', type: 'number', defaultValue: 30, unit: '%', slider: { min: 5, max: 95, step: 5 }, helpText: 'Higher tolerance removes similar colors around edges' },
    ],
    outputs: [{ name: 'result', label: 'Sanitized PNG', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'heic-to-jpg',
    slug: 'heic-to-jpg',
    title: 'HEIC to JPG Converter',
    description: 'Convert Apple HEIC photos to standard JPG format locally for full compatibility on all devices.',
    category: 'image',
    icon: 'RefreshCw',
    seo: {
      title: 'HEIC to JPG Converter Online - Convert HEIC Free',
      description: 'Convert iPhone HEIC photos to compatible JPEGs client-side. Fast, secure, and private.',
      keywords: ['convert heic to jpg', 'apple heic converter', 'iphone photos to jpeg', 'heic viewer online'],
      overview: 'Apple devices save space by storing photos in HEIC format. However, standard websites and software require JPEG. This tool converts your files securely inside the browser.',
      howToUse: ['Upload an Apple .heic photo.', 'Press convert.', 'Download the compatible JPEG file.'],
      examples: [{ input: { file: 'photo.heic' }, output: { format: 'JPEG' }, explanation: 'Converts iPhone HEIC photo to standard JPEG format.' }],
      faqs: [{ question: 'Are my iPhone photos safe?', answer: 'Yes! The conversion happens entirely locally in your browser. No photo bytes leave your computer.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload Apple HEIC File', type: 'file', defaultValue: null },
    ],
    outputs: [{ name: 'result', label: 'JPEG Image', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'webp-converter',
    slug: 'webp-converter',
    title: 'WebP Converter',
    description: 'Convert standard images (PNG, JPEG, GIF) to modern WebP format for faster web performance.',
    category: 'image',
    icon: 'FileCode',
    seo: {
      title: 'WebP Converter Online - PNG & JPEG to WebP',
      description: 'Convert image assets to the modern WebP format client-side. Maximize website speeds.',
      keywords: ['convert to webp', 'webp converter', 'png to webp', 'jpeg to webp', 'modern image formats'],
      overview: 'WebP is a modern image format providing superior lossless and lossy compression for web assets. Converting JPG/PNG to WebP shrinks site asset payloads significantly.',
      howToUse: ['Upload a PNG or JPEG file.', 'Convert the file.', 'Download your optimized WebP image.'],
      examples: [{ input: { file: 'hero.png' }, output: { format: 'WebP', sizeReduction: '60%' }, explanation: 'Converts PNG to WebP, decreasing asset load size by over half.' }],
      faqs: [{ question: 'Which browsers support WebP?', answer: 'All modern browsers (Chrome, Safari, Firefox, Edge) fully support WebP images.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload Image File', type: 'file', defaultValue: null },
    ],
    outputs: [{ name: 'result', label: 'WebP Image', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
];
