import { Tool } from '@/types/tool';

export const pdfTools: Tool[] = [
  {
    id: 'pdf-merge',
    slug: 'pdf-merge',
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into a single document securely inside your browser.',
    category: 'pdf',
    icon: 'FileCode',
    seo: {
      title: 'Merge PDF Online - Combine PDF Files Free',
      description: 'Combine multiple PDF documents into one single file. 100% private client-side processing.',
      keywords: ['merge pdf', 'combine pdf', 'join pdf documents', 'free pdf joiner'],
      overview: 'Merging PDF files organizes separate scanned documents, reports, or chapters into a single file for sharing. Our tool executes 100% in the browser using WebAssembly and Javascript, so your documents are never uploaded to any server.',
      howToUse: ['Select or drag-and-drop multiple PDF files.', 'Reorder the files if needed.', 'Click Merge to save your combined PDF.'],
      examples: [{ input: { filesCount: 3 }, output: { mergedPdfSize: '1.2 MB' }, explanation: 'Merging three separate project invoices compiles them into a unified invoice dossier.' }],
      faqs: [{ question: 'Is my data secure?', answer: 'Yes! All merging is performed client-side using pdf-lib. No files are transferred over the internet.' }],
    },
    inputs: [
      { name: 'files', label: 'Upload PDF Files', type: 'file', defaultValue: null, helpText: 'Upload 2 or more PDF documents.' },
    ],
    outputs: [{ name: 'result', label: 'Merged PDF File', type: 'text' }],
    calculate: async () => {
      return { status: 'custom_render_required' };
    },
  },
  {
    id: 'pdf-split',
    slug: 'pdf-split',
    title: 'Split PDF',
    description: 'Extract specific pages or split a PDF file into separate individual documents.',
    category: 'pdf',
    icon: 'Scissors',
    seo: {
      title: 'Split PDF Online - Extract PDF Pages',
      description: 'Split PDF documents by page ranges or extract all pages into separate files. Secure client-side execution.',
      keywords: ['split pdf', 'extract pdf pages', 'cut pdf document', 'separate pdf pages'],
      overview: 'Splitting large PDFs lets you extract relevant sheets or separate long contracts into individual sections without server uploads.',
      howToUse: ['Upload a PDF file.', 'Specify the page ranges (e.g. 1-3, 5) or choose to extract all pages.', 'Click Split to download the extracted files.'],
      examples: [{ input: { file: 'report.pdf', range: '2-4' }, output: { splitCount: 1 }, explanation: 'Extracts pages 2, 3, and 4 from a 10-page document into a new PDF.' }],
      faqs: [{ question: 'Can I split password-protected PDFs?', answer: 'You must provide the correct password to unlock the document before splitting.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload PDF File', type: 'file', defaultValue: null },
      { name: 'range', label: 'Page Range (e.g. 1-3, 5)', type: 'text', defaultValue: '1-2', placeholder: 'e.g. 1-5' },
    ],
    outputs: [{ name: 'result', label: 'Extracted PDF files', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'pdf-compress',
    slug: 'pdf-compress',
    title: 'Compress PDF',
    description: 'Reduce the file size of your PDF documents while maintaining optimal resolution and quality.',
    category: 'pdf',
    icon: 'FolderArchive',
    seo: {
      title: 'Compress PDF Online - Reduce PDF File Size',
      description: 'Shrink PDF file size for easier email sharing. Maintain document clarity without server uploads.',
      keywords: ['compress pdf', 'reduce pdf size', 'shrink pdf document', 'pdf optimizer'],
      overview: 'Large PDFs with images can be difficult to email. Compression re-samples images and removes metadata bloating, yielding a smaller file footprint.',
      howToUse: ['Select a PDF file.', 'Choose compression level (Low, Medium, High).', 'Download the optimized file.'],
      examples: [{ input: { file: 'catalog.pdf', level: 'medium' }, output: { reduction: '45%' }, explanation: 'Compresses a 10MB PDF down to 5.5MB.' }],
      faqs: [{ question: 'Does compression lower text quality?', answer: 'Text layers remain perfectly sharp; only large embedded raster images are optimized.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload PDF File', type: 'file', defaultValue: null },
      {
        name: 'level',
        label: 'Compression Level',
        type: 'select',
        defaultValue: 'medium',
        options: [
          { label: 'Low (High quality, larger size)', value: 'low' },
          { label: 'Medium (Balanced)', value: 'medium' },
          { label: 'High (Smallest size, lower image quality)', value: 'high' },
        ],
      },
    ],
    outputs: [{ name: 'result', label: 'Compressed PDF file', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'pdf-rotate',
    slug: 'pdf-rotate',
    title: 'Rotate PDF',
    description: 'Rotate skewed PDF pages 90, 180, or 270 degrees and download the corrected document.',
    category: 'pdf',
    icon: 'RotateCw',
    seo: {
      title: 'Rotate PDF Online - Turn PDF Pages Free',
      description: 'Rotate individual or all pages of a PDF document. Real-time visual layout adjustments.',
      keywords: ['rotate pdf', 'turn pdf pages', 'rotate pages online', 'fix skewed pdf'],
      overview: 'Scanned documents sometimes compile upside down or in landscape orientation. Rotating these pages makes them readable.',
      howToUse: ['Upload a PDF document.', 'Click the rotation buttons on individual pages.', 'Click Save to download the corrected document.'],
      examples: [{ input: { angle: 90 }, output: { status: 'Rotated 90° Clockwise' }, explanation: 'Fixes a landscape-scanned page to portrait.' }],
      faqs: [{ question: 'Can I rotate just one page?', answer: 'Yes, our visual interface lets you select and rotate specific pages individually.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload PDF File', type: 'file', defaultValue: null },
      {
        name: 'angle',
        label: 'Default Rotation Angle',
        type: 'select',
        defaultValue: 90,
        options: [
          { label: '90° Clockwise', value: 90 },
          { label: '180° Flip', value: 180 },
          { label: '90° Counter-Clockwise', value: 270 },
        ],
      },
    ],
    outputs: [{ name: 'result', label: 'Rotated PDF file', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    title: 'PDF to Word',
    description: 'Convert PDF files to editable Microsoft Word document format directly.',
    category: 'pdf',
    icon: 'FileText',
    seo: {
      title: 'PDF to Word Converter - Edit PDF in Word',
      description: 'Convert PDF files to docx format. Retain page flow, layouts, and text formatting.',
      keywords: ['pdf to word', 'convert pdf to docx', 'editable pdf', 'pdf to doc'],
      overview: 'Converting a PDF to a Word document translates rigid layout blocks into editable flow text and paragraphs for word processor adjustments.',
      howToUse: ['Upload a PDF file.', 'Click convert to process layout structures.', 'Download the resulting DOCX.'],
      examples: [{ input: { file: 'resume.pdf' }, output: { format: 'DOCX' }, explanation: 'Generates an editable Word resume from the PDF file.' }],
      faqs: [{ question: 'Does this read scanned text?', answer: 'Standard conversion processes selectable text layers. Scanned text requires our PDF OCR tool instead.' }],
    },
    inputs: [{ name: 'file', label: 'Upload PDF File', type: 'file', defaultValue: null }],
    outputs: [{ name: 'result', label: 'Word File (.docx)', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    title: 'Word to PDF',
    description: 'Convert Microsoft Word DOCX files into standard high-fidelity PDF documents.',
    category: 'pdf',
    icon: 'FileCode',
    seo: {
      title: 'Word to PDF Converter - Convert Docx to PDF',
      description: 'Compile Word documents into standardized PDF layouts ensuring perfect formatting.',
      keywords: ['word to pdf', 'convert docx to pdf', 'word to pdf online', 'free docx converter'],
      overview: 'Word files can render differently depending on fonts and software versions. Compiling them to PDF freezes the layout, guaranteeing identical presentation on all screens.',
      howToUse: ['Upload your DOCX file.', 'Click convert.', 'Download the generated PDF.'],
      examples: [{ input: { file: 'agreement.docx' }, output: { format: 'PDF' }, explanation: 'Converts editable agreement to printable PDF.' }],
      faqs: [{ question: 'Are fonts preserved?', answer: 'Yes, standard document fonts are embedded directly within the PDF file structure.' }],
    },
    inputs: [{ name: 'file', label: 'Upload Word File (.docx)', type: 'file', defaultValue: null }],
    outputs: [{ name: 'result', label: 'PDF Document', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'pdf-ocr',
    slug: 'pdf-ocr',
    title: 'PDF OCR Text Extractor',
    description: 'Perform Optical Character Recognition (OCR) to extract editable text from scanned PDFs or images.',
    category: 'pdf',
    icon: 'ScanText',
    seo: {
      title: 'PDF OCR Online - Extract Text from Scanned PDFs',
      description: 'Convert scanned PDF documents or image files into searchable, selectable text. 100% browser-based OCR.',
      keywords: ['pdf ocr', 'optical character recognition', 'extract text from scan', 'image to text pdf'],
      overview: 'Scanned sheets are represented as static images, meaning search tools cannot index their contents. OCR analyzes character shapes to rebuild text layers.',
      howToUse: ['Upload a scanned PDF or photo.', 'Select language (e.g. English).', 'Download the text document or copy results.'],
      examples: [{ input: { file: 'receipt.pdf' }, output: { textLength: '350 characters' }, explanation: 'Identifies item prices and text details from scanned invoice.' }],
      faqs: [{ question: 'Does this run server-side?', answer: 'No, this uses Tesseract.js in a Web Worker, preserving complete confidentiality.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload Scanned File (PDF or Image)', type: 'file', defaultValue: null },
      {
        name: 'lang',
        label: 'Recognition Language',
        type: 'select',
        defaultValue: 'eng',
        options: [
          { label: 'English', value: 'eng' },
          { label: 'Spanish', value: 'spa' },
          { label: 'French', value: 'fra' },
          { label: 'German', value: 'deu' },
        ],
      },
    ],
    outputs: [{ name: 'extractedText', label: 'Extracted Text', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'pdf-signer',
    slug: 'pdf-signer',
    title: 'Sign PDF',
    description: 'Add a handwritten digital signature or initials to your PDF documents securely.',
    category: 'pdf',
    icon: 'Signature',
    seo: {
      title: 'Sign PDF Online - Draw or Upload Signatures',
      description: 'Draw, type, or upload an image signature and burn it directly into your PDF agreements.',
      keywords: ['sign pdf', 'digital signature pdf', 'draw signature online', 'e-sign agreements'],
      overview: 'Electronic signatures speed up remote agreements. Draw your signature or upload initials and place them on the page canvases.',
      howToUse: ['Upload a PDF document.', 'Draw or type your signature.', 'Drag the signature box onto any page.', 'Save the signed PDF.'],
      examples: [{ input: { file: 'lease.pdf' }, output: { status: 'Signed' }, explanation: 'Burns a signature onto the final page of a lease document.' }],
      faqs: [{ question: 'Are these signatures legally binding?', answer: 'Yes, simple e-signatures are legally recognized under ESIGN and eIDAS for standard commercial transactions.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload PDF to Sign', type: 'file', defaultValue: null },
    ],
    outputs: [{ name: 'result', label: 'Signed PDF Document', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'pdf-watermark',
    slug: 'pdf-watermark',
    title: 'PDF Watermark',
    description: 'Add text or image watermarks to all pages of your PDF document for copyright protection.',
    category: 'pdf',
    icon: 'Stamp',
    seo: {
      title: 'Add PDF Watermark - Protect PDF Documents',
      description: 'Stamps custom text watermark or logo overlays onto your PDF sheets. Adjust font sizes and opacity.',
      keywords: ['pdf watermark', 'add watermark to pdf', 'protect pdf copyrights', 'stamp pdf pages'],
      overview: 'Watermarking labels files as proprietary drafts or confidential records. This overlay helps prevent unauthorized duplication.',
      howToUse: ['Select a PDF file.', 'Type your watermark text or upload a PNG logo.', 'Adjust opacity, angle, and position.', 'Download file.'],
      examples: [{ input: { file: 'spec.pdf', text: 'CONFIDENTIAL', opacity: 30 }, output: { watermarked: true }, explanation: 'Stamps translucent "CONFIDENTIAL" text diagonally across all pages.' }],
      faqs: [{ question: 'Can the watermark be easily removed?', answer: 'Our tool embeds watermarks directly into the page content stream, making them permanent.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload PDF File', type: 'file', defaultValue: null },
      { name: 'text', label: 'Watermark Text', type: 'text', defaultValue: '', placeholder: 'DRAFT' },
      { name: 'opacity', label: 'Opacity (%)', type: 'number', defaultValue: 30, unit: '%', slider: { min: 10, max: 90, step: 5 } },
    ],
    outputs: [{ name: 'result', label: 'Watermarked PDF file', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'pdf-protector',
    slug: 'pdf-protector',
    title: 'Protect PDF',
    description: 'Encrypt your PDF documents with a strong password to prevent unauthorized viewing.',
    category: 'pdf',
    icon: 'Lock',
    seo: {
      title: 'Password Protect PDF - Encrypt PDF Documents',
      description: 'Secure PDF files with strong standard passwords. Restrict printing, copying, and edits.',
      keywords: ['protect pdf', 'encrypt pdf', 'pdf password generator', 'lock pdf file'],
      overview: 'Sensitive documents need encryption. Adding a password locks the content, requiring viewers to authenticate before rendering pages.',
      howToUse: ['Select your PDF document.', 'Enter a strong access password.', 'Click Protect and download the locked PDF.'],
      examples: [{ input: { file: 'report.pdf', password: 'SecretPassword123' }, output: { encrypted: true }, explanation: 'Locks report.pdf so it asks for the password upon opening.' }],
      faqs: [{ question: 'What encryption standard is used?', answer: 'We compile PDFs using standard RC4/AES encryption levels compatible with Acrobat Reader.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload PDF File', type: 'file', defaultValue: null },
      { name: 'password', label: 'Set Access Password', type: 'text', defaultValue: '', placeholder: 'Minimum 6 characters' },
    ],
    outputs: [{ name: 'result', label: 'Encrypted PDF file', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
  {
    id: 'pdf-eraser',
    slug: 'pdf-eraser',
    title: 'Erase PDF Content',
    description: 'Redact or whiteout text, signatures, and images in your PDF files securely.',
    category: 'pdf',
    icon: 'Eraser',
    seo: {
      title: 'Erase PDF Content Online - Redact PDF Free',
      description: 'Whiteout text, logos, or signatures in your PDF files. Perform secure local PDF redacts in the browser.',
      keywords: ['pdf eraser', 'erase text in pdf', 'whiteout pdf', 'redact pdf free', 'remove signature from pdf'],
      overview: 'Erasing sensitive details, text paragraphs, or logos secures private documents before distributing them. Our browser-side whiteout tool draws solid white blocks on top of coordinates locally.',
      howToUse: ['Select a PDF file.', 'Click and drag on the preview page to draw whiteout boxes over elements you want to erase.', 'Click Erase Content & Save to compile and download your updated PDF.'],
      examples: [{ input: { file: 'doc.pdf', erasures: 2 }, output: { erased: true }, explanation: 'Permanently whited out two social security number occurrences on the document.' }],
      faqs: [{ question: 'Does this delete text metadata?', answer: 'This stamps a permanent solid white layer over selected areas. For complete security, we recommend running OCR or flattening your PDF if you need to strip searchable text paths.' }],
    },
    inputs: [
      { name: 'file', label: 'Upload PDF to Edit', type: 'file', defaultValue: null },
    ],
    outputs: [{ name: 'result', label: 'Erased PDF Document', type: 'text' }],
    calculate: async () => ({ status: 'custom_render_required' }),
  },
];
