uploads = []
generated = []

[[outputs]]
id = "Vdry02sCYq7oODkxf_6Rf"
uri = "file://artifacts/utilityhub-video/public/audio/vo_reveal.mp3"
type = "audio"
title = "reveal voiceover"

[[outputs]]
id = "mNTzHAjGke4tAVoN3YHA4"
uri = "file://artifacts/utilityhub-video/public/audio/vo_problem.mp3"
type = "audio"
title = "problem voiceover"

[[outputs]]
id = "dPhsrc1TdQXYZOt5PO0iY"
uri = "file://artifacts/utilityhub-video/public/audio/vo_intro.mp3"
type = "audio"
title = "intro voiceover"

[[outputs]]
id = "NAzmR0lKcTBHyeR70tv6N"
uri = "file://artifacts/utilityhub-video/public/audio/vo_outro.mp3"
type = "audio"
title = "outro voiceover"

[[outputs]]
id = "sAM0i-AcgPoxgUaVNjmce"
uri = "file://artifacts/utilityhub-video/public/audio/vo_value.mp3"
type = "audio"
title = "value voiceover"

[[outputs]]
id = "vv9DNcDXQLZYC1Y_8ak60"
uri = "file://artifacts/utilityhub-video/public/audio/vo_demo_emi.mp3"
type = "audio"
title = "demo_emi voiceover"

[[outputs]]
id = "3br8hVDTfJUandKq9XI8g"
uri = "file://artifacts/utilityhub-video/public/audio/vo_demo_json.mp3"
type = "audio"
title = "demo_json voiceover"

[[outputs]]
id = "o72ATXiYA5mte_JyVpX34"
uri = "file://artifacts/utilityhub-video/public/audio/vo_demo_bmi.mp3"
type = "audio"
title = "demo_bmi voiceover"
