// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/utilityhub-home/Bold.tsx": () => import("../components/mockups/utilityhub-home/Bold.tsx"),
  "./components/mockups/utilityhub-home/Editorial.tsx": () => import("../components/mockups/utilityhub-home/Editorial.tsx"),
  "./components/mockups/utilityhub-home/Minimal.tsx": () => import("../components/mockups/utilityhub-home/Minimal.tsx")
};
